### PR TITLE
[Bug] #128 : Implement favourite button UI in detail modal

### LINKED ISSUE #128: [Bug] 상세 정보 보기 즐겨찾기 개선
# Bug note
> Step-by-step explanation of what situation occurred from the start to the bug

1. 착한 가격 업소를 누른다. (맵의 어노테이션 / 가게 리스트)
2. 즐겨찾기 목록에 추가하려고 하트 버튼을 누른다.
3. 영역이 너무 작아 클릭이 잘 되지 않는다.

- 즐겨찾기 목록 추가 버튼과 터치 영역을 더 크게 만든다.

### PR DESCRIPTION
**Pull request by imparang**
# Issue Number
🔒 Close #128 

## New features

- 상세 정보 모달에서 즐겨찾기 버튼 개선

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

### CODE REVIEW

File: DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift [hunk 1]
```diff
@@ -32,6 +32,10 @@ class DetailModalViewController: ModalViewController {
     
     lazy var favoriteButton: UIButton = {
         let button = UIButton()
+        button.setImage(UIImage(systemName: "heart", withConfiguration: UIImage.SymbolConfiguration(scale: .large)), for: .normal)
```
Comment (sustainable-git) [inline DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift:35]: 좋은 코드네요!

**Review by sustainable-git — APPROVED** [review]
LGTM
